apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-backend-java-deployment
  labels:
    app: e-commerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-app
  template:
    metadata:
      labels:
        app: e-commerce-app
    spec:
      containers:
        - name: my-e-commerce-backend-java
          image: dhanushaperera07/e-commerce-app-backend:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: mongodb.database.url
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_SECRET_DATABASE_URL
            - name: mongodb.database.name
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_SECRET_DATABASE_NAME


---

apiVersion: v1
kind: Service
metadata:
  name: e-commerce-backend-java-service
spec:
  type: NodePort
  selector:
    app: e-commerce-app
  ports:
    - name: my-nodeport
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000