apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGODB_SECRET_DATABASE_URL: bW9uZ29kYitzcnY6Ly9zbGlpdC1zdHVkZW50OnNsaWl0LXN0dWRlbnRAY2x1c3RlcjAuZDN5bDIubW9uZ29kYi5uZXQvZV9jb21tZXJjZV9hcHA/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  MONGODB_SECRET_DATABASE_NAME: ZV9jb21tZXJjZV9hcHA=